import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        friday: {
          bg: 'var(--bg-primary)',
          surface: 'var(--bg-surface)',
          secondary: 'var(--bg-secondary)',
          tertiary: 'var(--bg-tertiary)',
          elevated: 'var(--bg-elevated)',
          border: 'var(--border-default)',
          'border-hover': 'var(--border-hover)',
          'border-active': 'var(--border-active)',
          'border-subtle': 'var(--border-subtle)',
          accent: 'var(--accent-primary)',
          'accent-hover': 'var(--accent-hover)',
          'accent-glow': 'var(--accent-glow)',
          'text-primary': 'var(--text-primary)',
          'text-secondary': 'var(--text-secondary)',
          'text-muted': 'var(--text-muted)',
          'text-tertiary': 'var(--text-muted)',
          'text-accent': 'var(--text-accent)',
          active: 'var(--status-success)',
          error: 'var(--status-error)',
          pending: 'var(--status-warning)',
          info: 'var(--status-info)',
        },

        /* --- Browserbase-native semantic tokens (Phase 2 migration target) --- */
        bg: 'var(--bg)',
        surface: 'var(--surface)',
        'surface-2': 'var(--surface-2)',
        'surface-accent': 'var(--surface-accent)',
        'surface-sunken': 'var(--surface-sunken)',
        border: 'var(--border)',
        'border-strong': 'var(--border-strong)',
        'border-accent': 'var(--border-accent)',
        text: 'var(--text)',
        'text-muted': 'var(--text-muted)',
        'text-subtle': 'var(--text-subtle)',
        accent: 'var(--accent)',
        'accent-hover': 'var(--accent-hover)',
        'accent-pressed': 'var(--accent-pressed)',
        'accent-fg': 'var(--accent-fg)',
        'accent-fg-strong': 'var(--accent-fg-strong)',
        'accent-text': 'var(--accent-text)',
        success: 'var(--success)',
        'success-fg': 'var(--success-fg)',
        'success-tint': 'var(--success-tint)',
        warning: 'var(--warning)',
        'warning-fg': 'var(--warning-fg)',
        'warning-tint': 'var(--warning-tint)',
        error: 'var(--error)',
        'error-fg': 'var(--error-fg)',
        'error-tint': 'var(--error-tint)',
        info: 'var(--info)',
        'info-fg': 'var(--info-fg)',
        'info-tint': 'var(--info-tint)',
        neutral: 'var(--neutral)',
        'neutral-fg': 'var(--neutral-fg)',
        'neutral-tint': 'var(--neutral-tint)',
        scrim: 'var(--scrim)',
        'wc-red': 'var(--wc-red)',
        'wc-yellow': 'var(--wc-yellow)',
        'wc-green': 'var(--wc-green)',
      },
      fontFamily: {
        sans: ['var(--font-geist-sans)', 'system-ui', '-apple-system', 'sans-serif'],
        display: ['var(--font-display, var(--font-geist-sans))', 'system-ui', 'sans-serif'],
        mono: ['var(--font-geist-mono)', 'JetBrains Mono', 'Fira Code', 'monospace'],
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        full: 'var(--radius-full)',
        pill: 'var(--radius-pill)',
        sharp: 'var(--radius-sharp)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        glow: 'var(--shadow-glow)',
        glass: 'var(--glass-shadow)',
        'glass-elevated': 'var(--glass-shadow-elevated)',
        overlay: 'var(--shadow-overlay)',
        pop: 'var(--shadow-pop)',
      },
      backdropBlur: {
        glass: 'var(--glass-blur)',
        'glass-heavy': 'var(--glass-blur-heavy)',
        'glass-subtle': 'var(--glass-blur-subtle)',
      },
      animation: {
        orbit: 'orbit calc(var(--duration) * 1s) linear infinite',
      },
      keyframes: {
        orbit: {
          '0%': {
            transform: 'rotate(0deg) translateY(calc(var(--radius) * 1px)) rotate(0deg)',
          },
          '100%': {
            transform: 'rotate(360deg) translateY(calc(var(--radius) * 1px)) rotate(-360deg)',
          },
        },
      },
      spacing: {
        'fri-1': 'var(--space-1)',
        'fri-2': 'var(--space-2)',
        'fri-3': 'var(--space-3)',
        'fri-4': 'var(--space-4)',
        'fri-6': 'var(--space-6)',
        'fri-8': 'var(--space-8)',
        'fri-12': 'var(--space-12)',
      },
    },
  },
  plugins: [],
};

export default config;
